language: node_js

node_js:
 - iojs
 - 0.12
 - 0.11
 - 0.10

script: npm run travis

before_install:
  - sudo apt-get update
  - sudo apt-get --yes install python3 php5-curl php5-cli

after_script:
  - npm run coverage
  - npm run codeclimate
