language: node_js

node_js:
 - 0.12
 - "iojs"

script: npm test

before_install:
  - sudo apt-get update
  - sudo apt-get --yes install python3 php5-curl php5-cli

after_script:
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha
  - ./node_modules/.bin/codeclimate < coverage/lcov.info
