language: node_js

node_js:
 - 0.12
 - "iojs"

script: npm test

after_script:
  - ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha
  - ./node_modules/.bin/codeclimate < coverage/lcov.info
